### ISSUE TITLE
ERROR: unknown simbol in the beginning of the sigar string

### ISSUE THREAD

**Issue by francicco** [uio-bmi/NucBreak#2]
Hi,

I'm testing NucBreak. I'm separately aligning my pairs with BWA with the following command line:

`bwa mem -t $THREADS $ASSEMBLY.fasta $GENOMICR1 | samtools view -@ $THREADS -Sb - | samtools sort -@ $THREADS - | samtools view -@ $THREADS -h > $ASSEMBLY.DNA.Aligned.P1.sortedByCoord.out.bam`

and then I execute NucBreak with this command:

`python $NucBREAK --min_frag_size 180 --sam_1 $ASSEMBLY.DNA.Aligned.P1.sortedByCoord.out_.bam --sam_2 $ASSEMBLY.DNA.Aligned.P2.sortedByCoord.out_.bam $ASSEMBLY.fasta $GENOMICR1 $GENOMICR2 $ASSEMBLY.NucBREAK Test.NucBREAK`

Unfortunately I get this error.

```
H
ERROR: unknown simbol in the beginning of the sigar string
Traceback (most recent call last):
  File "/home/fc464/software/NucBreak/nucbreak.py", line 92, in <module>
    main()
  File "/home/fc464/software/NucBreak/nucbreak.py", line 90, in main
    START(args)
  File "/home/fc464/software/NucBreak/nucbreak.py", line 55, in START
    min_ins_size, max_ins_size, read_length,read_groups_dict, asmb_seq_dict=insert_size.FIND_INSERT_SIZE_VALUES(pe_sam_1,pe_sam_2,working_dir+'Fragment_size_distr.txt',min_frag_size, max_frag_size)
  File "/home/fc464/software/NucBreak/insert_size.py", line 342, in FIND_INSERT_SIZE_VALUES
    insertion_size_dict, read_length, read_groups_dict, asmb_seq_dict=PARSE_SAM_FILES(pe_sam_1,pe_sam_2)
  File "/home/fc464/software/NucBreak/insert_size.py", line 132, in PARSE_SAM_FILES
    append_line=general.FIND_LINE(temp1)
  File "/home/fc464/software/NucBreak/general.py", line 118, in FIND_LINE
    return [map_flag_dict[map_flag],ref_name,ref_st,ref_end,read_st, read_end, cigar,nm,qual_ascii_33]
KeyError: 2064
```
Any help?

Thanks
F

**Comment by kseniakh** [comment]
Hi francicco,

NucBreak expects that a sam file is generated by bowtie2 and not bwa. 

I would advise you to run NucBreak without sam files in input. In this case Bowtie2 will be run automatically and you don't need to care about the proper input parameter settings for Bowtie2 and sam file sorting.

Ksenia

**Comment by francicco** [comment]
Hi Ksenia,

Thank you for your reply. I tried to use NucBreak to run the alignment, unfortunately, it seems like bowtie gets stuck. Maybe I can try to run myself the bowtie stage and give the output to NucBreak.
Would that work?

Best,
F

**Comment by kseniakh** [comment]
you can run bowtie yourself but be sure that it is run with  "--sensitive_local --ma 1 -a" parameter settings and the output sam files are sorted by read names and not the coordinates.

Ksenia

**Comment by francicco** [comment]
Ok! Thank you!
F
